
(FUNC, void, main, -)
(ALLOC, x, main -)
(LOAD, $t0, x, -)
(SOM, $t1, 1, 2)
(SOM, $t2, $t1, 3)
(SOM, $t3, $t2, 4)
(COMP, $t4, $t0, $t3)
(IFF, $t4, L0 -)
(LOAD, $t5, 0, -)
(RET, $t5, -, -)
(GOTO, L1, -, -)
(LAB, L0, -, -)
(GOTO, L1, -, -)
(LAB, L1, -, -)
(END, main, -, -)
